version: '3.9'

x-php: &php
  environment:
    USER_ID: ${USER_ID:-}
    GROUP_ID: ${GROUP_ID:-}
  build:
    context: docker/php
    target: dev

services:
  web:
    image: nginx:1.21-alpine
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      DOMAIN: ${DOMAIN}
    depends_on:
      - temporal-web
    links:
      - temporal-web
    labels:
      com.dnsdock.alias: ${DOMAIN},admin-${DOMAIN},web-${DOMAIN}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./runtime/web/logs:/var/log/nginx

  php-cli:
    <<: *php
    links:
      - temporal
    volumes:
      - ./app:/app
      - ./runtime/php-cli:/runtime
    build:
      context: docker/php
      target: dev

  rr:
    <<: *php
    links:
      - temporal
    volumes:
      - ./app:/app
      - ./runtime/rr:/runtime
    command: ["./rr", "serve"]

  db:
    image: postgres:13
    labels:
      com.dnsdock.alias: db-${DOMAIN}
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app

  temporal:
    image: temporalio/auto-setup:1.10.2
    depends_on:
      - db
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=app
      - POSTGRES_PWD=app
      - POSTGRES_SEEDS=db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    volumes:
      - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    image: temporalio/admin-tools:1.10.2
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true

  temporal-web:
    image: temporalio/web:1.10.0
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true

